config/routes.rb
Rails.application.routes.draw do

	resources :orders
	resources :items
	resources :conversations do
		resources :messages
	end
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => "home#index"
  root to: "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  belongs_to :order, optional: true
end

app/models/message.rb
class Message < ApplicationRecord

	belongs_to :conversation
	belongs_to :user
	validates_presence_of :body, :conversation_id, :user_id
	def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, length: {minimum:4, maximum: 12}
  has_many :items, dependent: :destroy
  has_many :goods_sold, class_name: 'Order', foreign_key: :seller_id
  has_many :purchases, class_name: 'Order', foreign_key: :buyer_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_perimitted_parameters, if: :devise_controller?
  # adding custom fields for User signup and edit.
  def configure_perimitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:fname, :lname, :username, :seller])
    devise_parameter_sanitizer.permit(:account_update, keys:[:fname, :lname, :username, :seller])
  end
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	def index
		@users = User.all
		@conversations = Conversation.all
	end
	def create
		if Conversation.between(params[:sender_id],params[:recipient_id])
			.present?
			@conversation = Conversation.between(params[:sender_id],
				params[:recipient_id]).first
		else
			@conversation = Conversation.create!(conversation_params)
		end
		redirect_to conversation_messages_path(@conversation)
	end
	private
	def conversation_params
		params.permit(:sender_id, :recipient_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	respond_to do |format|
  		format.html
  	end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)
    @item.seller_id = current_user.id
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :location, :image)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action do
		@conversation = Conversation.find(params[:conversation_id])
	end
	def index
		@messages = @conversation.messages
		if @messages.length > 10
			@over_ten = true
			@messages = @messages[-10..-1]
		end
		if params[:m]
			@over_ten = false
			@messages = @conversation.messages
		end
		if @messages.last
			if @messages.last.user_id != current_user.id
				@messages.last.read = true;
			end
		end
		@message = @conversation.messages.new
	end
	def new
		@message = @conversation.messages.new
	end
	def create
		@message = @conversation.messages.new(message_params)
		if @message.save
			redirect_to conversation_messages_path(@conversation)
		end
	end
	private
	def message_params
		params.require(:message).permit(:body, :user_id)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(buyer_id: current_user.id)
    @items = Item.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @item = Item.all
  end

  # GET /orders/new
  def new
    @item = Item.find(params[:item])
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @item = Item.find(params[:item])
    @order = Order.new(
      buyer_id: current_user.id,
      seller_id: @item.seller_id,
      status: "Order request sent",
      item_id: @item.id
      )

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:buyer_id, :seller_id, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/Home/_login.html.erb
<section class="module parallax parallax-1">
  <div class="container">
    <img src="/assets/logo.png" id = "logo"></img>
  </div>
</section>

<section class="module content">
  <div class="home-box center-block">
    <div class="prompt row">
      <h3>Choose Your Role:</h3>
    </div>
    <a href="/items">
      <div class="role" id= "buyer">
        BUYER
      </div>
    </a>
    <a href="/items/new">
      <div class="role" id= "seller">
        SELLER
      </div>
    </a>
  </div>
</section>

<section class="module parallax parallax-2">
  <div class="container">
    <h1>Community</h1>
  </div>
</section>

<section class="module content">
  <div class="container">
    <h2>WHO ARE WE ?</h2>
    <p>We thought you might like to know a bit more of what we're all about. Retros-Otros launched in New York City back in 1875 as a local classified ads and community platform, designed to connect people who were either planning to sell, or buy second hand items.
    </p>
    <p>
      We've grown a lot since then through word of mouth and we're proud to say that Retros-Otros is now loved by its ever growing community. We are the second hand store that now spans 5 boroughs across New York City. Our aim at Retros-Otros is to give you a simple and easy-to-use tool that lets you quickly find the second hand items you are looking for.
    </p>
  </div>
</section>

<section class="module parallax parallax-3">
  <div class="container">
    <h1>Preserve</h1>
  </div>
</section>

<section class="module content">
  <div class="container">
    <h2>OUR MISSION:</h2>
    <p>
      Second-hand stuff leaves you more open to whatever your own personal style is rather than feeling dictated to by shops.
    </p>
    <p>
      <strong>Sophie Ellis-Bextor</strong>
    </p>
    <p>
      The mission of Retros Otros is to promote consumption of second hand goods to conserve Earths' natural resources which all life depends on.

      Our vision is a world where the diversity of life thrives, and people act to conserve nature for its own sake and its ability to fulfill our needs and enrich our lives.</p>

      <p>How do we achieve this mission and vision?</p>
      <ul>
        <li> Through the dedicated efforts of our diverse staff, including more than 600 scientists, all of whom impact conservation in 69 countries.</li>
        <li>With the help of our many partners, from individuals and governments to local nonprofits and corporations.</li>
        <li>By using a non-confrontational, collaborative approach and staying true to our five unique core values.</li>
      </ul>


      <p>That’s how Retro Otros has done more than anyone else to advance conservation around the world since our founding in 1875.</p>
  </div>
</section>

<%if current_user%>

  <%else%>
  <section class="module content" id="register">
    <div class="home-box center-block">
      <div class="prompt row">
        <h3 class="login">Please Register/Sign-in to proceed</h3>
      </div>
    </div>
  </section>
  <%end%>
</section>

app/views/Home/_notlogged.html.erb
<section class="module parallax parallax-1">
  <div class="container">
    <img src="/assets/logo.png" id = "logo"></img>
  </div>
  </section>

<section class="module content">
  <div class="container">
    <h2>OUR MISSION!</h2>
    <p>
      Second-hand stuff leaves you more open to whatever your own personal style is rather than feeling dictated to by shops.
    </p>
    <p>
      <strong>Sophie Ellis-Bextor</strong>
    </p>
    <p>
      The mission of Retros Otros is to promote consumption of second hand goods to conserve Earths' natural resources which all life depends on.

      Our vision is a world where the diversity of life thrives, and people act to conserve nature for its own sake and its ability to fulfill our needs and enrich our lives.</p>

      <p>How do we achieve this mission and vision?</p>
      <ul>
        <li> Through the dedicated efforts of our diverse staff, including more than 600 scientists, all of whom impact conservation in 69 countries.</li>

        <li>With the help of our many partners, from individuals and governments to local nonprofits and corporations.</li>

        <li>By using a non-confrontational, collaborative approach and staying true to our five unique core values.</li>
      </ul>


      <p>That’s how Retro Otros has done more than anyone else to advance conservation around the world since our founding in 1875.</p>
  </div>
  </section>

<section class="module parallax parallax-2">
  <div class="container">
    <h1>Community</h1>
  </div>
</section>

<section class="module content">
  <div class="container">
    <h2>WHO ARE WE ?</h2>
    <p>We thought you might like to know a bit more of what we're all about. Retros-Otros launched in New York City back in 1875 as a local classified ads and community platform, designed to connect people who were either planning to sell, or buy second hand items.
    </p>
    <p>
      We've grown a lot since then through word of mouth and we're proud to say that Retros-Otros is now loved by its ever growing community. We are the second hand store that now spans 5 boroughs across New York City. Our aim at Retros-Otros is to give you a simple and easy-to-use tool that lets you quickly find the second hand items you are looking for.
    </p>
  </div>
</section>

<section class="module parallax parallax-3">
  <div class="container">
    <h1>Preserve</h1>
  </div>
  </section>


<section class="module content" id="register">
    <div class="home-box center-block">
      <div class="prompt row">
        <h3 class="login">Please Register/Sign-in to proceed</h3>
      </div>
    </div>
  </section>

app/views/Home/index.html.erb
<%if current_user%>
  <%=render "login"%>
<%else%>
  <%=render "notlogged"%>
<%end%>

app/views/conversations/index.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>

  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <%= link_to recipient.username, conversation_messages_path(conversation)%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
      <div class="item">
        <%= user.username %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-wrapper">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'filestyle', id: 'file', 
       :'data-classButton' => 'btn btn-primary',
       :'data-input' => 'false', classIcon:  'icon-plus',
       :'data-buttonText' => 'Upload Image' %>
  </div>



  <div class="actions">
    <%= f.submit "Create Item", class: "btn btn-primary btn-mdn" %>
  </div>
</div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class='item-wrapper row'>
  <h1>Items</h1>
  <% @items.reverse.each do |item| %>
    <div class="item">
      <!--#This is the top of the post  -->
      <div class="item-head">
        <div class="name">
          <%=item.user.username%>
        </div>
        <div class="timestamp">
          <%=time_ago_in_words item.created_at%> ago.
        </div>

      </div>
      <% if current_user.purchases.map{|o| o.item.id }.include? item.id %>
        <%= link_to new_order_path(item: item.id) do %>
        <div class="p-image item_<%=item.id%> center-block" style='background-image: url("<%=item.image%>)'></div>
        <% end %>
        <p><%=item.name%></p>
        <p>Offer Made!</p>
      <%else%>
        <%= link_to new_order_path(item: item.id) do %>
        <div class="p-image item_<%=item.id%>, center-block" style='background-image: url("<%=item.image%>")'></div>
        <% end %>
        <p><%=item.name%></p>
        <p>$<%=item.price%>0</p>
      <%end%>

      <%if item.user_id == current_user.id%>
        <%= link_to 'Show', item, class: "item-button" %>
        |
        <%= link_to 'Edit', edit_item_path(item), class: "item-button" %>
        |
        <%= link_to 'Destroy', item, class: "item-button", method: :delete, data: { confirm: 'Are you sure?' } %>
      <%else%>
        <%= link_to 'Show', item, class: "item-button" %>
      <%end%>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="overlay">
  <div class="login-form">

<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path, class: "btn btn-primary btn-mdn" %>
</div>
</div>

app/views/items/show.html.erb
  <div class="detail-wrapper">
    <div class="detail-show">
      <h3><%=@item.name%></h3>
      <div class="show-image item_<%=@item.id%>" style='background-image: url("<%=@item.image%>")'></div>

      <div class="info">
        <div class="left">

          <p>
            <strong>Price:</strong>
            <%= @item.price %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= @item.description %>
          </p>

          <p>
            <strong>Location:</strong>
            <%= @item.location %>
          </p>
        </div>
      </div>
    </div>
    <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-primary btn-md" %> |
    <%= link_to 'Back', items_path, class: "btn btn-primary btn-md" %>
  </div>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-default navbar-fixed-top'>
  <div class="navbar-container">
    <div class="navbar-header">
      <button type="button" name="button" class='navbar-toggle collapsed' data-target= '#bs-navbar-collapse-1' data-toggle="collapse">
        <span class='sr-only'>Toggle Navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
    </div>
    <div id="bs-navbar-collapse-1" class="collapse navbar-collapse">
      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <li><%= link_to "Browse", items_path%></li>
          <li><%=link_to "My Orders", orders_path%></li>
          <li> <%=link_to "New Item", new_item_path%> </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li> <%=link_to "Login", new_user_session_url%> </li>
          <li> <%=link_to "Register", new_user_registration_path %> </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RetrosOtros</title>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon"  href="https://s-media-cache-ak0.pinimg.com/originals/cb/44/96/cb44963c111c4223df5e42660c0bba8f.png" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="spacer"></div>
    <%=render "layouts/navbar"%>
   <!--  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<% if @over_ten %>
   <%= link_to 'Show Previous', '?m=all' %>
<% end %>

<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <div class="item">
        <div class="content">
          <div class="header-msg"><strong><%= user.username %></strong> <%= message.message_time %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon-msg"></i>
              <%= message.body %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
  <div>
    <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
  </div>

<% end %>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
<%= hidden_field_tag :item, item.id %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="detail-wrapper">
    <div class="detail-show">

      <div class="show-image item_<%=@item.id%>" style='background-image: url("<%=@item.image%>")'></div>

      <div class="info">
        <div class="left">
          <p>
            <strong>Name:</strong>
            <%= @item.name %>
          </p>

          <p>
            <strong>Price:</strong>
            <%= @item.price %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= @item.description %>
          </p>

          <p>
            <strong>Location:</strong>
            <%= @item.location %>
          </p>
        </div>
      </div>
      <% if current_user.purchases.map{|o| o.item.id }.include? item.id %>
        Offer Pending!
      <%else%>
        <%=f.submit "Make an Offer", class: "btn btn-primary btn-md"%>
      <%end%>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container">
  <h1>Orders</h1>
  <% @orders.each do |order| %>
    <div class="orders row">
      <h3><%=order.item.name%></h3>
      <div class="o-image" style='background-image: url("<%=order.item.image%>)'></div>

      <div class="order-info">
        <p><%= order.status %> for <%= order.item.name%></p>
        <p>Order was made <%=time_ago_in_words order.created_at%> ago</p>
        <strong><p>$<%=order.item.price%>0</p></strong>
        <p><%=order.item.description%></p>

      </div>
      <div class="order-links">
        <%= link_to 'Destroy Order', order, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
  <%= "No orders" if @orders.empty? %>
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order, item: @item %>

app/views/orders/show.html.erb
<div class="overlay-order-confirmation">
	<div class="layout-order-confirmation">
	<P><strong class="header">ORDER CONFIRMATION</strong></P>

		<p>
			<strong class="header">Buyer Username:</strong>
			<%= current_user.username %>
		</p>

		<p>
			<strong class="header">Seller Username:</strong>
			<%= @order.item.user.username %>
		</p>

		<p>
			<strong class="header">Item:</strong>
			<%= @order.item.name %>
		</p>

		<p>
			<strong class="header">Price (USD):</strong>
			<%= @order.item.price %>
		</p>

		<p>
			<strong class="header">Status:</strong>
			<%= @order.status %>
		</p>

		<%= link_to 'View other items', items_path %>
	</div>
</div>